### ISSUE TITLE
Not bad

### ISSUE THREAD

**Issue by LazarevSergey** [DaniellRosberg/Task01#1]
Для начала, не плохо.

Теперь о печальке: один из тестов невозможно запустить, без дополнительных действий. Посмотри, что с ним не так.

Небольшая рекомендация: в репозитории есть "мусор", почитай про .gitignore и используй его для удаления из репозитория этого "мусора"

**Comment by DaniellRosberg** [comment]
@LazarevSergey сделано, залил изменения и пост запрос
